"""CSV and single-file HTML reporting."""
from __future__ import annotations

import csv
import html
import json
import os
from typing import Dict, List, Sequence


def flatten(record: Dict, prefix: str = "") -> Dict:
    """Flatten one nested metric record into a single CSV row."""
    flat: Dict = {}
    for key, value in record.items():
        name = f"{prefix}{key}"
        if isinstance(value, dict):
            if all(isinstance(k, int) for k in value):     # e.g. value_fractions
                for k, v in value.items():
                    flat[f"{name}_{k}"] = v
            else:
                flat.update(flatten(value, prefix=f"{name}."))
        elif isinstance(value, (list, tuple)):
            flat[name] = json.dumps(list(value))
        else:
            flat[name] = value
    return flat


def write_csv(records: Sequence[Dict], path: str) -> None:
    rows = [flatten(r) for r in records]
    if not rows:
        open(path, "w").close()
        return
    fields: List[str] = []
    for row in rows:
        for key in row:
            if key not in fields:
                fields.append(key)
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def write_json(obj, path: str) -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w") as handle:
        json.dump(obj, handle, indent=2, default=str)


_CSS = """
:root{--bg:#fbfaf8;--fg:#20201d;--mut:#5d5b55;--line:#ddd9d2;--warn:#8a3a12;--ok:#1f5c34}
*{box-sizing:border-box}
body{margin:0;padding:2.5rem 1.5rem;background:var(--bg);color:var(--fg);
     font:16px/1.6 ui-serif,Georgia,'Times New Roman',serif;max-width:64rem;margin-inline:auto}
h1{font-size:1.9rem;margin:0 0 .3rem}
h2{font-size:1.25rem;margin:2.4rem 0 .8rem;padding-bottom:.3rem;border-bottom:1px solid var(--line)}
p.sub{color:var(--mut);margin:0 0 2rem}
table{border-collapse:collapse;width:100%;font:14px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace}
th,td{text-align:left;padding:.4rem .6rem;border-bottom:1px solid var(--line);vertical-align:top}
th{font-weight:600;color:var(--mut);white-space:nowrap}
td.num{text-align:right;font-variant-numeric:tabular-nums}
.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(11rem,1fr));gap:.9rem;margin:1rem 0}
.card{border:1px solid var(--line);border-radius:6px;padding:.9rem 1rem;background:#fff}
.card .v{font:600 1.5rem/1.2 ui-monospace,Menlo,monospace;font-variant-numeric:tabular-nums}
.card .k{color:var(--mut);font-size:.8rem;text-transform:uppercase;letter-spacing:.04em}
.warn{color:var(--warn)} .ok{color:var(--ok)}
.scroll{overflow-x:auto}
footer{margin-top:3rem;color:var(--mut);font-size:.85rem}
"""


def _card(key: str, value: str, cls: str = "") -> str:
    return (
        f'<div class="card"><div class="k">{html.escape(key)}</div>'
        f'<div class="v {cls}">{html.escape(str(value))}</div></div>'
    )


def _table(rows: Sequence[Dict], columns: Sequence[str], limit: int = 40) -> str:
    head = "".join(f"<th>{html.escape(c)}</th>" for c in columns)
    body = []
    for row in rows[:limit]:
        cells = []
        for column in columns:
            value = row.get(column, "")
            if isinstance(value, float):
                cells.append(f'<td class="num">{value:.4g}</td>')
            elif isinstance(value, int):
                cells.append(f'<td class="num">{value}</td>')
            else:
                cells.append(f"<td>{html.escape(str(value))}</td>")
        body.append("<tr>" + "".join(cells) + "</tr>")
    return f'<div class="scroll"><table><thead><tr>{head}</tr></thead><tbody>{"".join(body)}</tbody></table></div>'


def write_html(
    title: str,
    subtitle: str,
    headline: Sequence[tuple],
    sections: Sequence[tuple],
    path: str,
) -> None:
    """``headline`` is [(key, value, css_class)]; ``sections`` is
    [(heading, prose, rows, columns)]."""
    parts = [
        "<!doctype html><meta charset='utf-8'>",
        f"<title>{html.escape(title)}</title>",
        f"<style>{_CSS}</style>",
        f"<h1>{html.escape(title)}</h1>",
        f"<p class='sub'>{html.escape(subtitle)}</p>",
        '<div class="cards">'
        + "".join(_card(k, v, c) for k, v, c in headline)
        + "</div>",
    ]
    for heading, prose, rows, columns in sections:
        parts.append(f"<h2>{html.escape(heading)}</h2>")
        if prose:
            parts.append(f"<p>{prose}</p>")
        if rows:
            parts.append(_table(rows, columns))
    parts.append(
        "<footer>Generated by "
        "<a href='https://github.com/rodriguescarson/labelscope'>labelscope</a>"
        " — MIT licensed.</footer>"
    )
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w") as handle:
        handle.write("\n".join(parts))
